############# English navigation ##############

# -- Main Menu --
# The "main" menu is used in the new index.html template to generate your links.

[[main]]
name = "CV"
url = "/cv.pdf"
weight = 10

[[main]]
name = "Medical Diffusion Model Demo"
url = "https://diffusion.danedelste.in/"
weight = 20

[[main]]
name = "2048 AI Demo"
url = "https://2048.danedelste.in/"
weight = 30

#[[main]]
#name = "Blog"
#url = "/blog/"
#weight = 30


# footer menu
#[[footer]]
#name = "About"
#url = "/about"
#weight = 1